app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix: /

fos_user:
    resource: "@UserBundle/Resources/config/routing.yml"

oauth:
    resource: "@AppBundle/Resources/config/oauth/routing.yml"
    prefix:  /oauth

sonata:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin