security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        main:
            pattern: ^/
            form_login:
                check_path: /login_check
                login_path: /login
                provider: fos_userbundle
#                success_handler: authentication_handler
#                failure_handler: authentication_handler
#                csrf_provider: form.csrf_provider
#            oauth:
#                failure_path:  /oauth/connect
#                login_path:    /oauth/login
#                check_path:    /
#                oauth_user_provider: [fos_userbundle]
#                resource_owners:
#                    google:   /oauth/login/check-google
#                    facebook: /oauth/login/check-facebook

            logout:
                path: /logout
                target: /
            anonymous: ~

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN