<?php

namespace Events\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProfileRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ProfileRepository extends EntityRepository
{
}
