app_comment:
    resource: "@AppBundle/Resources/config/routing/comment.yml"
    prefix:   /comment

app_event:
    resource: "@AppBundle/Resources/config/routing/event.yml"
    prefix:   /event

app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

app_user:
    resource: "@AppBundle/Resources/config/user/routing.yml"
    prefix:   /user
